export const mockPlaces = [
  {
    "name": "코엑스",
    "address": "서울 강남구 영동대로 513",
    "lat": 37.511,
    "lng": 127.059
  },
  {
    "name": "강남역",
    "address": "서울 강남구 강남대로 396",
    "lat": 37.4979,
    "lng": 127.0276
  },
  {
    "name": "서울역",
    "address": "서울 용산구 한강대로 405",
    "lat": 37.5547,
    "lng": 126.9707
  },
  {
    "name": "홍대입구",
    "address": "서울 마포구 양화로 160",
    "lat": 37.5572,
    "lng": 126.9245
  },
  {
    "name": "인천공항",
    "address": "인천 중구 공항로 272",
    "lat": 37.4602,
    "lng": 126.4407
  },
  {
    "name": "건국대학교 서울캠퍼스",
    "address": "서울 광진구 능동로 120",
    "lat": 37.5408,
    "lng": 127.0793
  }
];
export const parkingLots = [
  {
    "id": "PARK_COEX_001",
    "name": "탄천공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 삼성동 171",
    "jibunAddress": "서울 강남구 삼성동 171",
    "lat": 37.5119,
    "lng": 127.0661,
    "capacity": 996,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1200,
    "additionalMinutes": 10,
    "additionalFee": 400,
    "dayPassMinutes": 360,
    "dayPassFee": 12000,
    "monthlyFee": 120000,
    "paymentMethods": "카드, 현금",
    "notes": "공영주차장 요금은 현장 정책에 따라 달라질 수 있습니다.",
    "agencyName": "서울시설공단",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-21",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_TANCHEON",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_COEX_002",
    "name": "코엑스몰 주차장",
    "publicPrivateType": "민영",
    "parkingType": "부설",
    "roadAddress": "서울 강남구 영동대로 513",
    "jibunAddress": "서울 강남구 삼성동 159",
    "lat": 37.5126,
    "lng": 127.0591,
    "capacity": 2500,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 3000,
    "additionalMinutes": 15,
    "additionalFee": 1500,
    "dayPassMinutes": null,
    "dayPassFee": null,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "매장 이용 할인은 방문 매장 정책을 확인하세요.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-21",
    "source": "공공데이터포털 샘플",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_COEX_003",
    "name": "삼성역 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 테헤란로 지하",
    "jibunAddress": "서울 강남구 삼성동",
    "lat": 37.5089,
    "lng": 127.0632,
    "capacity": 82,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "05:00",
    "weekdayClose": "23:30",
    "saturdayOpen": "05:00",
    "saturdayClose": "23:30",
    "holidayOpen": "05:00",
    "holidayClose": "23:30",
    "feeType": "유료",
    "baseMinutes": 5,
    "baseFee": 400,
    "additionalMinutes": 5,
    "additionalFee": 400,
    "dayPassMinutes": 300,
    "dayPassFee": 18000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "소규모 공영주차장으로 혼잡할 수 있습니다.",
    "agencyName": "강남구청",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-20",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_SAMSUNG",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_COEX_004",
    "name": "봉은사 인근 민영주차장",
    "publicPrivateType": "민영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 봉은사로 524",
    "jibunAddress": "서울 강남구 삼성동",
    "lat": 37.5151,
    "lng": 127.0576,
    "capacity": 46,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "07:00",
    "weekdayClose": "22:00",
    "saturdayOpen": "08:00",
    "saturdayClose": "22:00",
    "holidayOpen": "08:00",
    "holidayClose": "21:00",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 2000,
    "additionalMinutes": 10,
    "additionalFee": 700,
    "dayPassMinutes": 420,
    "dayPassFee": 20000,
    "monthlyFee": null,
    "paymentMethods": "카드, 현금",
    "notes": "운영시간은 현장 상황에 따라 달라질 수 있습니다.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": false,
    "dataDate": "2026-04-30",
    "source": "공공데이터포털 샘플",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_GANGNAM_001",
    "name": "강남역 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 강남대로 396",
    "jibunAddress": "서울 강남구 역삼동",
    "lat": 37.4982,
    "lng": 127.0278,
    "capacity": 96,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1800,
    "additionalMinutes": 10,
    "additionalFee": 600,
    "dayPassMinutes": 420,
    "dayPassFee": 17000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "혼잡 시간대에는 만차 가능성이 있습니다.",
    "agencyName": "강남구청",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-18",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_GANGNAM",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_SEOUL_STATION_001",
    "name": "서울역 서부 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 중구 청파로 426",
    "jibunAddress": "서울 중구 봉래동",
    "lat": 37.5562,
    "lng": 126.9691,
    "capacity": 210,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1500,
    "additionalMinutes": 10,
    "additionalFee": 500,
    "dayPassMinutes": 420,
    "dayPassFee": 14000,
    "monthlyFee": 120000,
    "paymentMethods": "카드",
    "notes": "서울역 주변 공영주차장 샘플입니다.",
    "agencyName": "서울시 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_STATION_WEST",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_SEOUL_STATION_002",
    "name": "서울역 민영주차장",
    "publicPrivateType": "민영",
    "parkingType": "부설",
    "roadAddress": "서울 용산구 한강대로 405",
    "jibunAddress": "서울 용산구 동자동",
    "lat": 37.5543,
    "lng": 126.9716,
    "capacity": 95,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "06:00",
    "weekdayClose": "23:30",
    "saturdayOpen": "06:00",
    "saturdayClose": "23:30",
    "holidayOpen": "07:00",
    "holidayClose": "22:00",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 2500,
    "additionalMinutes": 10,
    "additionalFee": 800,
    "dayPassMinutes": 360,
    "dayPassFee": 22000,
    "monthlyFee": null,
    "paymentMethods": "카드, 현금",
    "notes": "민영주차장 샘플입니다. 실제 할인은 현장 확인이 필요합니다.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": false,
    "dataDate": "2026-06-17",
    "source": "샘플 데이터",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_HONGDAE_001",
    "name": "홍대입구 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 마포구 양화로 160",
    "jibunAddress": "서울 마포구 동교동",
    "lat": 37.5578,
    "lng": 126.9237,
    "capacity": 142,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1800,
    "additionalMinutes": 10,
    "additionalFee": 600,
    "dayPassMinutes": 420,
    "dayPassFee": 18000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "홍대입구 주변 공영주차장 샘플입니다.",
    "agencyName": "마포구 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_HONGDAE",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_HONGDAE_002",
    "name": "홍대 상상마당 인근 주차장",
    "publicPrivateType": "민영",
    "parkingType": "노외",
    "roadAddress": "서울 마포구 어울마당로",
    "jibunAddress": "서울 마포구 서교동",
    "lat": 37.5509,
    "lng": 126.9218,
    "capacity": 64,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "08:00",
    "weekdayClose": "23:00",
    "saturdayOpen": "08:00",
    "saturdayClose": "23:30",
    "holidayOpen": "09:00",
    "holidayClose": "22:00",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 3000,
    "additionalMinutes": 10,
    "additionalFee": 1000,
    "dayPassMinutes": 300,
    "dayPassFee": 25000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "민영 샘플입니다.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": false,
    "dataDate": "2026-06-17",
    "source": "샘플 데이터",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_ICN_AIRPORT_001",
    "name": "인천공항 단기주차장",
    "publicPrivateType": "공영",
    "parkingType": "부설",
    "roadAddress": "인천 중구 공항로 272",
    "jibunAddress": "인천 중구 운서동",
    "lat": 37.4606,
    "lng": 126.442,
    "capacity": 3500,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1200,
    "additionalMinutes": 15,
    "additionalFee": 600,
    "dayPassMinutes": 1440,
    "dayPassFee": 24000,
    "monthlyFee": null,
    "paymentMethods": "카드, 하이패스",
    "notes": "공항 주차 요금은 실제 운영기관 공지를 확인하세요.",
    "agencyName": "공항 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "샘플 데이터",
    "realtimeKey": "ICN_SHORT",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_ICN_AIRPORT_002",
    "name": "인천공항 장기주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "인천 중구 공항로 272",
    "jibunAddress": "인천 중구 운서동",
    "lat": 37.4559,
    "lng": 126.4498,
    "capacity": 6000,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 60,
    "baseFee": 1000,
    "additionalMinutes": 15,
    "additionalFee": 500,
    "dayPassMinutes": 1440,
    "dayPassFee": 12000,
    "monthlyFee": null,
    "paymentMethods": "카드, 하이패스",
    "notes": "장시간 주차에 유리한 샘플입니다.",
    "agencyName": "공항 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "샘플 데이터",
    "realtimeKey": "ICN_LONG",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_KONKUK_001",
    "name": "건국대학교병원 주차장",
    "publicPrivateType": "민영",
    "parkingType": "부설",
    "roadAddress": "서울 광진구 능동로 120-1",
    "jibunAddress": "서울 광진구 화양동",
    "lat": 37.5405,
    "lng": 127.0713,
    "capacity": 520,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 2000,
    "additionalMinutes": 10,
    "additionalFee": 500,
    "dayPassMinutes": 480,
    "dayPassFee": 25000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "건국대학교 주변 샘플 후보입니다. 실제 요금과 운영시간은 현장 기준을 확인하세요.",
    "agencyName": "샘플 운영사",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "로컬 샘플 주차장",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_KONKUK_002",
    "name": "스타시티몰 주차장",
    "publicPrivateType": "민영",
    "parkingType": "부설",
    "roadAddress": "서울 광진구 아차산로 272",
    "jibunAddress": "서울 광진구 자양동",
    "lat": 37.5388,
    "lng": 127.0736,
    "capacity": 1100,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1500,
    "additionalMinutes": 10,
    "additionalFee": 500,
    "dayPassMinutes": 420,
    "dayPassFee": 22000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "건대입구 인근 샘플 후보입니다. 매장 할인은 현장 정책을 확인하세요.",
    "agencyName": "샘플 운영사",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "로컬 샘플 주차장",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_KONKUK_003",
    "name": "화양동 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 광진구 능동로 18길",
    "jibunAddress": "서울 광진구 화양동",
    "lat": 37.546,
    "lng": 127.0734,
    "capacity": 84,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1200,
    "additionalMinutes": 10,
    "additionalFee": 400,
    "dayPassMinutes": 360,
    "dayPassFee": 12000,
    "monthlyFee": 90000,
    "paymentMethods": "카드, 현금",
    "notes": "공영주차장 샘플 후보입니다. 실제 할인 적용 여부는 관리기관 기준을 확인하세요.",
    "agencyName": "광진구 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "로컬 샘플 주차장",
    "realtimeKey": "SEOUL_KONKUK_PUBLIC",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_KONKUK_004",
    "name": "자양동 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 광진구 자양동",
    "jibunAddress": "서울 광진구 자양동",
    "lat": 37.5374,
    "lng": 127.0765,
    "capacity": 65,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1000,
    "additionalMinutes": 10,
    "additionalFee": 300,
    "dayPassMinutes": 420,
    "dayPassFee": 10000,
    "monthlyFee": 80000,
    "paymentMethods": "카드, 현금",
    "notes": "건국대학교 주변 공영 샘플 후보입니다. 실제 운영시간과 요금은 현장 기준을 확인하세요.",
    "agencyName": "광진구 샘플",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-06-17",
    "source": "로컬 샘플 주차장",
    "realtimeKey": "SEOUL_KONKUK_JAYANG",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  }
];
export const realtimeStatuses = [
  {
    "parkingLotId": "PARK_COEX_001",
    "availableSpaces": 23,
    "totalSpaces": 996,
    "observedAt": "2026-06-17T09:30:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_COEX_003",
    "availableSpaces": 5,
    "totalSpaces": 82,
    "observedAt": "2026-06-17T09:32:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_GANGNAM_001",
    "availableSpaces": 8,
    "totalSpaces": 96,
    "observedAt": "2026-06-17T09:35:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_SEOUL_STATION_001",
    "availableSpaces": 31,
    "totalSpaces": 210,
    "observedAt": "2026-06-17T09:40:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_HONGDAE_001",
    "availableSpaces": 12,
    "totalSpaces": 142,
    "observedAt": "2026-06-17T09:42:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_ICN_AIRPORT_001",
    "availableSpaces": 180,
    "totalSpaces": 3500,
    "observedAt": "2026-06-17T09:45:00+09:00",
    "source": "공항 주차 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_ICN_AIRPORT_002",
    "availableSpaces": 560,
    "totalSpaces": 6000,
    "observedAt": "2026-06-17T09:45:00+09:00",
    "source": "공항 주차 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_KONKUK_003",
    "availableSpaces": 23,
    "totalSpaces": 84,
    "observedAt": "2026-06-17T13:20:00+09:00",
    "source": "샘플 실시간"
  },
  {
    "parkingLotId": "PARK_KONKUK_004",
    "availableSpaces": 9,
    "totalSpaces": 65,
    "observedAt": "2026-06-17T13:20:00+09:00",
    "source": "샘플 실시간"
  }
];
