export const mockPlaces = [
  { name: '코엑스', address: '서울 강남구 영동대로 513', lat: 37.511, lng: 127.059 },
  { name: '강남역', address: '서울 강남구 강남대로 396', lat: 37.4979, lng: 127.0276 },
  { name: '서울역', address: '서울 용산구 한강대로 405', lat: 37.5547, lng: 126.9707 }
];
export const parkingLots = [
  {
    "id": "PARK_COEX_001",
    "name": "탄천공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 삼성동 171",
    "jibunAddress": "서울 강남구 삼성동 171",
    "lat": 37.5119,
    "lng": 127.0661,
    "capacity": 996,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1200,
    "additionalMinutes": 10,
    "additionalFee": 400,
    "dayPassMinutes": 360,
    "dayPassFee": 12000,
    "monthlyFee": 120000,
    "paymentMethods": "카드, 현금",
    "notes": "공영주차장 요금은 현장 정책에 따라 달라질 수 있습니다.",
    "agencyName": "서울시설공단",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-21",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_TANCHEON",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_COEX_002",
    "name": "코엑스몰 주차장",
    "publicPrivateType": "민영",
    "parkingType": "부설",
    "roadAddress": "서울 강남구 영동대로 513",
    "jibunAddress": "서울 강남구 삼성동 159",
    "lat": 37.5126,
    "lng": 127.0591,
    "capacity": 2500,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 3000,
    "additionalMinutes": 15,
    "additionalFee": 1500,
    "dayPassMinutes": null,
    "dayPassFee": null,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "매장 이용 할인은 방문 매장 정책을 확인하세요.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-21",
    "source": "공공데이터포털 샘플",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_COEX_003",
    "name": "삼성역 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 테헤란로 지하",
    "jibunAddress": "서울 강남구 삼성동",
    "lat": 37.5089,
    "lng": 127.0632,
    "capacity": 82,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "05:00",
    "weekdayClose": "23:30",
    "saturdayOpen": "05:00",
    "saturdayClose": "23:30",
    "holidayOpen": "05:00",
    "holidayClose": "23:30",
    "feeType": "유료",
    "baseMinutes": 5,
    "baseFee": 400,
    "additionalMinutes": 5,
    "additionalFee": 400,
    "dayPassMinutes": 300,
    "dayPassFee": 18000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "소규모 공영주차장으로 혼잡할 수 있습니다.",
    "agencyName": "강남구청",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-20",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_SAMSUNG",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  },
  {
    "id": "PARK_COEX_004",
    "name": "봉은사 인근 민영주차장",
    "publicPrivateType": "민영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 봉은사로 524",
    "jibunAddress": "서울 강남구 삼성동",
    "lat": 37.5151,
    "lng": 127.0576,
    "capacity": 46,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "07:00",
    "weekdayClose": "22:00",
    "saturdayOpen": "08:00",
    "saturdayClose": "22:00",
    "holidayOpen": "08:00",
    "holidayClose": "21:00",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 2000,
    "additionalMinutes": 10,
    "additionalFee": 700,
    "dayPassMinutes": 420,
    "dayPassFee": 20000,
    "monthlyFee": null,
    "paymentMethods": "카드, 현금",
    "notes": "운영시간은 현장 상황에 따라 달라질 수 있습니다.",
    "agencyName": "민영 운영사",
    "phone": "",
    "hasDisabledSpaces": false,
    "dataDate": "2026-04-30",
    "source": "공공데이터포털 샘플",
    "realtimeKey": null,
    "disabledDiscountRate": 0,
    "compactDiscountRate": 0,
    "evDiscountRate": 0
  },
  {
    "id": "PARK_GANGNAM_001",
    "name": "강남역 공영주차장",
    "publicPrivateType": "공영",
    "parkingType": "노외",
    "roadAddress": "서울 강남구 강남대로 396",
    "jibunAddress": "서울 강남구 역삼동",
    "lat": 37.4982,
    "lng": 127.0278,
    "capacity": 96,
    "operatingDays": "평일+토요일+공휴일",
    "weekdayOpen": "00:00",
    "weekdayClose": "23:59",
    "saturdayOpen": "00:00",
    "saturdayClose": "23:59",
    "holidayOpen": "00:00",
    "holidayClose": "23:59",
    "feeType": "유료",
    "baseMinutes": 30,
    "baseFee": 1800,
    "additionalMinutes": 10,
    "additionalFee": 600,
    "dayPassMinutes": 420,
    "dayPassFee": 17000,
    "monthlyFee": null,
    "paymentMethods": "카드",
    "notes": "혼잡 시간대에는 만차 가능성이 있습니다.",
    "agencyName": "강남구청",
    "phone": "",
    "hasDisabledSpaces": true,
    "dataDate": "2026-05-18",
    "source": "공공데이터포털 샘플",
    "realtimeKey": "SEOUL_GANGNAM",
    "disabledDiscountRate": 50,
    "compactDiscountRate": 50,
    "evDiscountRate": 50
  }
];
export const realtimeStatuses = [
  {
    "parkingLotId": "PARK_COEX_001",
    "availableSpaces": 23,
    "totalSpaces": 996,
    "observedAt": "2026-06-17T09:30:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_COEX_003",
    "availableSpaces": 5,
    "totalSpaces": 82,
    "observedAt": "2026-06-17T09:32:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  },
  {
    "parkingLotId": "PARK_GANGNAM_001",
    "availableSpaces": 8,
    "totalSpaces": 96,
    "observedAt": "2026-06-17T09:35:00+09:00",
    "source": "서울시 시영주차장 실시간 샘플"
  }
];
